/** @type {import('tailwindcss').Config} */
const pretendardStack = ["'Pretendard Variable'", "'Pretendard'", 'Inter', 'system-ui', 'sans-serif'];

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container-lowest': 'var(--color-surface-raised)',
        'surface-container-low': 'var(--color-surface-elevated)',
        'surface-container': 'var(--color-surface-muted)',
        'surface-container-high': 'var(--color-surface-subtle)',
        'surface-container-highest': 'var(--color-surface-strong)',
        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-strong)',
        secondary: 'var(--color-accent)',
        'secondary-container': 'var(--color-accent-strong)',
        tertiary: 'var(--color-text-muted)',
        'tertiary-container': 'var(--color-text-subtle)',
        outline: 'var(--color-border-strong)',
        'outline-variant': 'var(--color-border-subtle)',
        'on-background': 'var(--color-text)',
        'on-surface': 'var(--color-text)',
        'on-surface-variant': 'var(--color-text-muted)',
        'on-primary': 'var(--color-primary-contrast)',
        'on-primary-container': 'var(--color-primary-strong)',
        'on-secondary': 'var(--color-accent-contrast)',
        'on-secondary-container': 'var(--color-accent)',
        'on-tertiary': 'var(--color-text-inverse)',
        'on-tertiary-container': 'var(--color-text-subtle)',
        'primary-fixed': 'var(--color-primary-strong)',
        'primary-fixed-dim': 'var(--color-primary)',
        'secondary-fixed': 'var(--color-accent-strong)',
        'secondary-fixed-dim': 'var(--color-accent)',
        'tertiary-fixed': 'var(--color-text-muted)',
        'tertiary-fixed-dim': 'var(--color-text-subtle)',
        'surface-tint': 'var(--color-primary-strong)',

        'elegant-gold': 'var(--elegant-gold)',
        'elegant-gold-light': 'var(--elegant-gold-light)',
        'ray-dark': 'var(--ray-dark)',
        'ray-light': 'var(--elegant-gold-light)',
        'ray-body': 'var(--ray-body)',
        shell: {
          rail: 'var(--shell-rail)',
          canvas: 'var(--shell-canvas)',
          card: 'var(--shell-card)',
          line: 'var(--shell-line)',
        },
        'warm-gray': {
          50: 'var(--warm-gray-50)',
          100: 'var(--warm-gray-100)',
          200: 'var(--warm-gray-200)',
          300: 'var(--warm-gray-300)',
          400: 'var(--warm-gray-400)',
          500: 'var(--warm-gray-500)',
          600: 'var(--warm-gray-600)',
          700: 'var(--warm-gray-700)',
          800: 'var(--warm-gray-800)',
          900: 'var(--warm-gray-900)',
        },
      },
      fontFamily: {
        headline: pretendardStack,
        body: pretendardStack,
        label: pretendardStack,
        display: pretendardStack,
        brand: pretendardStack,
        serif: pretendardStack,
        sans: pretendardStack,
      },
      animation: {
        'fade-in': 'fade-in 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        float: 'float 6s ease-in-out infinite',
        'subtle-zoom': 'subtle-zoom 20s ease-in-out infinite',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'subtle-zoom': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
